name: Nashville Quotes
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14378
title: Nashville Quotes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#1b1b1b'
    - '#bdbdbd'
    - '#535353'
    - '#8d8d8d'
  brandStrength: 0.125
  lightness: 0.1526665713172406
  saturation: 0.5515612731687725
  rhythmicContrast: 0.6588519450742751
purpose: []
